DockerSetup:
  stage: setup
  script:
    - export DOCKER_HOST=$DOCKER_HOST
    - eval $(ssh-agent)
    - ssh-add -k /root/.ssh/privatekey
    - sleep 5

DockerBuild:
  stage: build
  script:
    - docker build -t steamcmd .

DockerRun:
  stage: run
  script:
    - docker run --rm --name steamcmd steamcmd

DockerCleanup:
  stage: cleanup
  script:
    - unset DOCKER_HOST



stages:
  - setup
  - build
  - run
  - cleanup