DockerSetup:
  stage: setup
  script:
    - export DOCKER_HOST=$DOCKER_HOST
    - eval $(ssh-agent)
    - ssh-add ~/.ssh/privatekey
    - docker build -t steamcmd .
    - docker run --rm --name steamcmd steamcmd
    - unset DOCKER_HOST


.DockerRun:
  stage: run
  script:
    - docker run --env $SteamAccountSecret --env $STEAM_USERNAME --env $STEAM_PASSWORD --rm --name steamcmd steamcmd

.DockerCleanup:
  stage: cleanup
  script:
    - unset DOCKER_HOST

stages:
  - setup
  #- run
  #- cleanup